// <auto-generated />
using System;
using LeagueApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeagueApp.Migrations
{
    [DbContext(typeof(LeagueContext))]
    partial class LeagueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Speler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Waarde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Spelers");
                });

            modelBuilder.Entity("Data.Models.Team", b =>
                {
                    b.Property<int>("Stamnummer")
                        .HasColumnType("int");

                    b.Property<string>("Bijnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stamnummer");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Data.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NieuweClubStamnummer")
                        .HasColumnType("int");

                    b.Property<int?>("OudeClubStamnummer")
                        .HasColumnType("int");

                    b.Property<int>("Prijs")
                        .HasColumnType("int");

                    b.Property<int?>("SpelerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NieuweClubStamnummer");

                    b.HasIndex("OudeClubStamnummer");

                    b.HasIndex("SpelerId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Data.Models.Speler", b =>
                {
                    b.HasOne("Data.Models.Team", "Team")
                        .WithMany("Spelers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Transfer", b =>
                {
                    b.HasOne("Data.Models.Team", "NieuweClub")
                        .WithMany()
                        .HasForeignKey("NieuweClubStamnummer");

                    b.HasOne("Data.Models.Team", "OudeClub")
                        .WithMany()
                        .HasForeignKey("OudeClubStamnummer");

                    b.HasOne("Data.Models.Speler", "Speler")
                        .WithMany()
                        .HasForeignKey("SpelerId");
                });
#pragma warning restore 612, 618
        }
    }
}
